TYPE: virtual
FLAVOR: cluster

odl_l3_agent: "Enable"

hosts:
  - name: host1
    roles:
      - controller
      - ha
      - odl

  - name: host2
    roles:
      - controller
      - ha
      - odl

  - name: host3
    roles:
      - controller
      - ha
      - odl

  - name: host4
    roles:
      - compute

  - name: host5
    roles:
      - compute
